name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - setup.cfg
      - tox.ini

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
#          - Windows
#          - MacOs
        py:
          # - "3.12.0-rc.2"
          - "3.11"
          - "3.10"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Docker compose up
        run: make docker-compose-up

      - name: Setup
        run: make setup

      - name: Test
        run: make test
