# https://github.com/marketplace/actions/pypi-publish
name: publish
on:
  release:
    types: [published]

jobs:
  test:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/unireport
    permissions:
      id-token: write
    timeout-minutes: 3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup
        run: make setup

      - name: Build
        run: make build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verify_metadata: false
          verbose: true
          print_hash: true
